pub mod ai;
pub mod dice;
pub mod dictionary;
pub mod help;
pub mod ip;
pub mod metar;
pub mod owoify;
pub mod ping;
pub mod posix;
pub mod qr;
pub mod register;
pub mod taf;
// pub mod uptime;
pub mod verse;
pub mod weather;

pub use ai::ai;
pub use dice::dice;
pub use dictionary::dictionary;
pub use help::help;
pub use ip::ip;
pub use metar::metar;
pub use owoify::owoify;
pub use ping::ping;
pub use posix::posix;
pub use qr::qr;
pub use register::register;
pub use taf::taf;
// pub use uptime::uptime;
pub use verse::verse;
pub use weather::weather;
